<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UngVienSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('ung_vien')->insert([
            [
                'id' => 1,
                'tin_tuyen_dung_id' => 1,
                'ma_ho_so' => 'UV001',
                'ho' => 'Phạm Văn',
                'ten' => 'D',
                'email' => 'phamvand@gmail.com',
                'so_dien_thoai' => '0987654321',
                'dia_chi' => '123 Đường ABC, Quận 1, TP.HCM',
                'ngay_sinh' => '1995-05-15',
                'gioi_tinh' => 'nam',
                'trinh_do_hoc_van' => 'Đại học',
                'so_nam_kinh_nghiem' => 2,
                'luong_hien_tai' => 8000000,
                'luong_mong_muon' => 12000000,
                'duong_dan_cv' => '/storage/cv/cv_pham_van_d.pdf',
                'thu_xin_viec' => 'Tôi mong muốn được làm việc tại công ty',
                'url_portfolio' => 'https://portfolio.phamvand.com',
                'url_linkedin' => 'https://linkedin.com/in/phamvand',
                'ky_nang' => json_encode(['PHP', 'Laravel', 'Vue.js']),
                'ngay_co_the_lam_viec' => '2025-07-01',
                'nguon_ung_tuyen' => 'website',
                'ten_nguoi_gioi_thieu' => null,
                'trang_thai' => 'phong_van',
                'diem_phong_van' => 8.5,
                'ghi_chu_phong_van' => 'Ứng viên có tiềm năng',
                'ly_do_tu_choi' => null,
                'nguoi_dung_id' => null,
                'thoi_gian_nop' => now()->subDays(10),
                'nguoi_cap_nhat_cuoi_id' => 1,
                'created_at' => now()->subDays(10),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'tin_tuyen_dung_id' => 2,
                'ma_ho_so' => 'UV002',
                'ho' => 'Nguyễn Thị',
                'ten' => 'E',
                'email' => 'nguyenthie@gmail.com',
                'so_dien_thoai' => '0976543210',
                'dia_chi' => '456 Đường XYZ, Quận 3, TP.HCM',
                'ngay_sinh' => '1998-08-20',
                'gioi_tinh' => 'nu',
                'trinh_do_hoc_van' => 'Cao đẳng',
                'so_nam_kinh_nghiem' => 1,
                'luong_hien_tai' => 6000000,
                'luong_mong_muon' => 9000000,
                'duong_dan_cv' => '/storage/cv/cv_nguyen_thi_e.pdf',
                'thu_xin_viec' => 'Em rất hứng thú với vị trí Marketing',
                'url_portfolio' => null,
                'url_linkedin' => 'https://linkedin.com/in/nguyenthie',
                'ky_nang' => json_encode(['Social Media', 'Content Writing', 'Adobe Photoshop']),
                'ngay_co_the_lam_viec' => '2025-06-15',
                'nguon_ung_tuyen' => 'facebook',
                'ten_nguoi_gioi_thieu' => null,
                'trang_thai' => 'trung_tuyen',
                'diem_phong_van' => 9.0,
                'ghi_chu_phong_van' => 'Ứng viên xuất sắc, tuyển ngay',
                'ly_do_tu_choi' => null,
                'nguoi_dung_id' => 6,
                'thoi_gian_nop' => now()->subDays(15),
                'nguoi_cap_nhat_cuoi_id' => 2,
                'created_at' => now()->subDays(15),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'tin_tuyen_dung_id' => 1,
                'ma_ho_so' => 'UV003',
                'ho' => 'Lê Minh',
                'ten' => 'F',
                'email' => 'leminhf@gmail.com',
                'so_dien_thoai' => '0965432109',
                'dia_chi' => '789 Đường DEF, Quận 5, TP.HCM',
                'ngay_sinh' => '1992-12-10',
                'gioi_tinh' => 'nam',
                'trinh_do_hoc_van' => 'Đại học',
                'so_nam_kinh_nghiem' => 4,
                'luong_hien_tai' => 15000000,
                'luong_mong_muon' => 18000000,
                'duong_dan_cv' => '/storage/cv/cv_le_minh_f.pdf',
                'thu_xin_viec' => 'Mong muốn phát triển kỹ năng tại công ty',
                'url_portfolio' => 'https://github.com/leminhf',
                'url_linkedin' => 'https://linkedin.com/in/leminhf',
                'ky_nang' => json_encode(['PHP', 'Node.js', 'React', 'Docker']),
                'ngay_co_the_lam_viec' => '2025-08-01',
                'nguon_ung_tuyen' => 'linkedin',
                'ten_nguoi_gioi_thieu' => null,
                'trang_thai' => 'tu_choi',
                'diem_phong_van' => 7.0,
                'ghi_chu_phong_van' => 'Yêu cầu mức lương cao',
                'ly_do_tu_choi' => 'Mức lương không phù hợp ngân sách',
                'nguoi_dung_id' => null,
                'thoi_gian_nop' => now()->subDays(20),
                'nguoi_cap_nhat_cuoi_id' => 1,
                'created_at' => now()->subDays(20),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'tin_tuyen_dung_id' => 3,
                'ma_ho_so' => 'UV004',
                'ho' => 'Trần Văn',
                'ten' => 'G',
                'email' => 'tranvang@gmail.com',
                'so_dien_thoai' => '0954321098',
                'dia_chi' => '321 Đường GHI, Quận 7, TP.HCM',
                'ngay_sinh' => '1990-03-25',
                'gioi_tinh' => 'nam',
                'trinh_do_hoc_van' => 'Đại học',
                'so_nam_kinh_nghiem' => 5,
                'luong_hien_tai' => 14000000,
                'luong_mong_muon' => 16000000,
                'duong_dan_cv' => '/storage/cv/cv_tran_van_g.pdf',
                'thu_xin_viec' => 'Có kinh nghiệm kế toán tổng hợp',
                'url_portfolio' => null,
                'url_linkedin' => null,
                'ky_nang' => json_encode(['Excel', 'MISA', 'Báo cáo tài chính']),
                'ngay_co_the_lam_viec' => '2025-09-01',
                'nguon_ung_tuyen' => 'gioi_thieu',
                'ten_nguoi_gioi_thieu' => 'Lê Văn C',
                'trang_thai' => 'da_xem',
                'diem_phong_van' => null,
                'ghi_chu_phong_van' => null,
                'ly_do_tu_choi' => null,
                'nguoi_dung_id' => null,
                'thoi_gian_nop' => now()->subDays(5),
                'nguoi_cap_nhat_cuoi_id' => 1,
                'created_at' => now()->subDays(5),
                'updated_at' => now(),
            ],
        ]);
    }
}
